# Generated by Django 3.0.7 on 2021-08-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_auto_20210624_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_types',
            field=models.CharField(choices=[('teacher', 'lecturer'), ('student', 'student')], default='student', max_length=10),
        ),
    ]
