# Generated by Django 3.0.7 on 2021-08-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_auto_20210807_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_types',
            field=models.CharField(choices=[('lecturer', 'lecturer'), ('student', 'student')], default='student', max_length=10),
        ),
    ]
