# Generated by Django 3.0.7 on 2021-08-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_auto_20210808_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_types',
            field=models.CharField(choices=[('lecturer', 'lecturer'), ('student', 'student')], default='lecturer', max_length=10),
        ),
    ]
