# Generated by Django 3.0.7 on 2021-08-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='position',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course_code',
            field=models.CharField(max_length=10, null=True, verbose_name='Course code'),
        ),
    ]
