# Generated by Django 3.0.7 on 2021-08-24 13:39

import curriculum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_auto_20210814_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='Assignment',
            field=models.FileField(blank=True, upload_to=curriculum.models.save_lesson_files, verbose_name='Assignment'),
        ),
    ]
