# Generated by Django 3.0.7 on 2021-08-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_auto_20210824_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='image',
        ),
    ]
