# Generated by Django 3.0.7 on 2021-08-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_remove_subject_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_id',
        ),
    ]
